---
title: "L2_dataAnalysis_CDCRdata_Nutrient_Dist"
author: "laís petri"
date: "2024-05-29"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
```

Loading R packages
```{r, echo=FALSE}
## data wrangling + plots
library(tidyverse) 
library(scales)
## correlation plots
library(ggcorrplot)
## models
library(rjags)
library(coda)
## color blind discrete colors
library(pals) 
```

Paths to import files, and export outputs
```{r}
workingdir <- getwd()
datain <- file.path(workingdir, "parameters/CoarseEnv_FieldsAB")
graph.wd <- file.path(workingdir, "figures")
parameters.wd <- file.path(workingdir, "parameters/CoarseEnv_FieldsAB_Slopes/litterMinus5y")
```

Importing dataset
```{r}
parameters0_NoDist <- read_csv(file.path(datain,"NoDist_Litter_FieldsAB_Minus5y_CoarseEnv_ParametersValues.csv")) %>% 
    mutate(exp = 1)

NoDist_mu_ntrt <- parameters0_NoDist %>% 
  filter(grepl("^mu_a_ntrt",parameter)) %>% 
  mutate(alpha = rep(1:4,times=9)) %>% 
  filter(alpha %in% c(2,3))

parameters0_Dist <- read_csv(file.path(datain,"Dist_Litter_FieldsAB_Minus5y_CoarseEnv_ParametersValues.csv")) %>% 
    mutate(exp = 2)

Dist_mu_ntrt <- parameters0_Dist %>% 
  filter(grepl("^mu_a_ntrt",parameter)) %>% 
  mutate(alpha = rep(1:4,times=9)) %>% 
  filter(alpha %in% c(2,3))

ntrt_qtt <- tibble(ntrt = c(1:9),
                       ntrt_qtt = c(0.0,1.0,2.0,3.4,5.4,9.5,17.0,27.2,0))

dataList <- list(
  tempData = NoDist_mu_ntrt %>% 
    filter(alpha == 3) %>% 
    bind_rows(filter(Dist_mu_ntrt, alpha == 3)) %>% 
    mutate(ntrt = rep(1:9, times = 2)) %>% 
    left_join(ntrt_qtt),

  precipData = NoDist_mu_ntrt %>% 
    filter(alpha == 2) %>% 
    bind_rows(filter(Dist_mu_ntrt, alpha == 2)) %>% 
    mutate(ntrt = rep(1:9, times = 2)) %>% 
    left_join(ntrt_qtt)
)
```

EDA
```{r}
dataList[[1]] %>% 
  ggplot(aes(x=ntrt_qtt, y = statistics.Mean, shape=as.factor(exp)))+
  geom_point(size=4, alpha=0.5)+
  geom_smooth(method = "lm")+
  ggtitle("Precip")

dataList[[2]] %>% 
  ggplot(aes(x=ntrt_qtt, y = statistics.Mean, shape=as.factor(exp)))+
  geom_point(size=4, alpha=0.5)+
  geom_smooth(method = "lm") +
  ggtitle("Temp")
```

General objects (model)
```{r}
n_burnin = 300000
n_iter = 150000
n_thin = 50
```

## Model

```{r}
for (i in 1:length(dataList)) {
  # Which variable?
  expName <- names(dataList)[i]

  # Organizing variables
  datamodel <- list(N = nrow(dataList[[i]]), # sample size
                  meanY = dataList[[i]]$statistics.Mean, # dependent variable
                  SDY = dataList[[i]]$statistics.SD, # standard deviation associated with response
                  exp = dataList[[i]]$exp, # experiment type 1=NoDist, 2 Dist
                  Nexp = max(dataList[[i]]$exp),
                  ntrt = dataList[[i]]$ntrt_qtt, # predictor, nutrient quantity
                  ntrtpred = c(seq(0,26,1),27.2),
                  Npred = length(c(seq(0,26,1),27.2))
                  )

  # Initials
  initials <- list(
    list(beta = c(rep(0, max(dataList[[i]]$exp))),
         alpha = c(rep(1, max(dataList[[i]]$exp)))),
    list(beta = c(rep(1, max(dataList[[i]]$exp))),
         alpha = c(rep(-1, max(dataList[[i]]$exp)))),
    list(beta = c(rep(-1, max(dataList[[i]]$exp))),
         alpha = c(rep(0, max(dataList[[i]]$exp))))
)

# Model
Model1 <- "
data{

  for(i in 1:N){
  tau_y[i]<-1/pow(SDY[i],2)
  } 
  
}

model{

for(i in 1:N){
  
  # Likelihood of response data
  meanY[i] ~ dnorm(mu_exp[i], tau_y[i])
  meanY.h[i] ~ dnorm(mu_exp[i], tau_y[i])
  residuals[i]<-meanY.h[i]-meanY[i]
  
  # mean model 
      mu_exp[i] <- alpha[exp[i]] + beta[exp[i]]*ntrt[i]
        
} 

  #priors
  

  for(i in 1:Nexp){
  beta[i] ~ dnorm(0,0.0001)
  alpha[i] ~ dnorm(0,0.0001)
  }
  
  # predictions
  for(i in 1:Nexp){
    for(j in 1:Npred){
       mu_exp.pred[i,j]<-alpha[i]+beta[i]*ntrtpred[j]
    }
  }


}" #end of model

# Compile
set.seed(500)
load.module("dic")
m <-jags.model(textConnection(Model1), 
               data=datamodel,
               n.chains=3, 
               inits = initials)

# Burn-in period of 100000 iterations
set.seed(500)
update(m, n_burnin)

# Model DIC value
set.seed(500)
DIC <- dic.samples(m, n.iter=1000, thin = 1, type = "pD")
DIC <- round(sum(DIC[["deviance"]]) + abs(sum(DIC[["penalty"]])),0)

# Running model and retrieving parameters
# Plot: Posterior distributions
set.seed(500)
parameters<-coda.samples(m, variable.names = c("alpha", # exp intercepts
                                               "beta", # exp ntrt effects
                                               "meanY.h", # replicated data for R2
                                               "residuals", # residuals
                                               "deviance",
                                               "mu_exp.pred"), 
                         n.iter = n_iter, # samples to be kept after burn in
                         thin = n_thin, # thinning rate, save every 50th iteration to reduce correlation between consecutive values in the chain, #50
) 
parameters0_Dist<-summary(parameters)

# Extract the parameter names
param_names <- varnames(parameters)

# Exclude repY and residuals
filtered_params <- param_names[!grepl("^repY\\[|^residuals\\[", param_names)]

# Plot only the selected parameters
pdf(paste0(file.path(parameters.wd, paste(c(expName, "_PosteriorDistributions.pdf"), collapse=""))))
par(mar = c(2, 2, 2, 2)) 
plot(parameters[, filtered_params])  # Subset parameters before plotting
dev.off()

# Exporting parameter values, predictions and residuals
Quantiles <- as.data.frame(parameters0_Dist[2]) %>% 
  mutate_if(is.numeric, round,digits=4) %>% 
  rownames_to_column(., var = "parameter") %>% select(1,2,6)

Stats <- as.data.frame(parameters0_Dist[1]) %>% 
  mutate_if(is.numeric, round,digits=4) %>% 
  rownames_to_column(., var = "parameter") %>% 
  select(1:3) %>% left_join(Quantiles)
write_csv(Stats, paste0(file.path(parameters.wd,paste(c(expName, "_ParametersValues.csv"), collapse=""))))

# Plot: predicted vs. observed to calculate R2
Metric <- dataList[[i]]$statistics.Mean
Mean_pred <- Stats %>% filter(grepl("^meanY",parameter)) %>% select(statistics.Mean)
Mean_pred <- Mean_pred$statistics.Mean

predModel <- cbind(Mean_pred, Metric) %>% as.data.frame()

fit <- lm(Metric ~ Mean_pred, data=predModel)

ggplot(data = predModel, aes(y = Metric, x = Mean_pred)) +
  stat_function(fun = function(x) predict(fit, newdata = data.frame(Mean_pred = x)),
                color = "black", linewidth = 2) +
  annotate(label = sprintf("y = %.3f + %.3f x\nR² = %.2f", coef(fit)[1], coef(fit)[2], summary(fit)$r.squared),
           geom = "text", x = max(Mean_pred)/4, y = max(Metric)/2, size = 5) +
  geom_point(shape=19,size=5,alpha=0.5) +
  # xlim(0,1300)+
  ylab("Observed values")+
  xlab("Predicted values")+ 
  theme_classic()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.y = element_text(size = 25),
        axis.text.x = element_text(size = 25),
        axis.title = element_text(size = 25),
        axis.line = element_line(colour = "black"))

ggsave(paste0(file.path(graph.wd,paste(c("CoarseEnv_Minus5y_Litter_",expName, "_ModelFit_BIOMASS_.png"), collapse=""))), plot = last_plot(), width=7, height=5, dpi = 300, units="in")

# Plot: residuals vs predicted to evaluate model
Metric_pred <- Stats %>% filter(grepl("^meanY",parameter)) %>% select(statistics.Mean)
Metric_pred <- Metric_pred$statistics.Mean
Residuals <- Stats %>% filter(grepl("^residuals",parameter)) %>% select(statistics.Mean)
Residuals <- Residuals$statistics.Mean

predModel <- cbind(Metric_pred, Residuals) %>% as.data.frame()

ggplot(data = predModel, aes(y = Residuals, x = Metric_pred)) +
  geom_hline(yintercept=0)+
  geom_point(shape=19,size=5,alpha=0.5) +
  ylab("Residuals")+
  xlab("Predicted values")+ 
  theme_classic()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.y = element_text(size = 25),
        axis.text.x = element_text(size = 25),
        axis.title = element_text(size = 25),
        axis.line = element_line(colour = "black"))

ggsave(paste0(file.path(graph.wd,paste(c("CoarseEnv_Minus5y_Litter_",expName, "_ModelResiduals_.png"), collapse=""))), plot = last_plot(), width=7, height=5, dpi = 300, units="in")

## Outputs
# saving model output
save.image(paste0(file.path(parameters.wd,paste(c(expName, "_CDCR_ModelOutput.RData"), collapse=""))))
}
```
